name: Release to npm
on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          cache: 'pnpm'
      - uses: pnpm/action-setup@v2
        with:
          version: '7.x'
      - run: pnpm install
      - run: npm ci --no-package-lock
      - run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
